name = "TauP"
uuid = "dd4fbf09-c66a-460f-850c-a6bf3253bb5f"
authors = ["bvanderbeek <brandon.p.vanderbeek@gmail.com>"]
version = "0.1.0"

[deps]
CatViews = "81a5f4ea-a946-549a-aa7e-2a7f63a27d31"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JavaCall = "494afd89-becb-516b-aafa-70d2670c0337"

[compat]
julia = "^1"
CatViews = "^1"
DSP = "^1"
DataStructures = "^1"
Interpolations = "^1"
JavaCall = "^1"