name = "TauP"
uuid = "dd4fbf09-c66a-460f-850c-a6bf3253bb5f"
authors = ["bvanderbeek <brandon.p.vanderbeek@gmail.com>"]
version = "0.1.0"

[deps]
CatViews = "81a5f4ea-a946-549a-aa7e-2a7f63a27d31"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JavaCall = "494afd89-becb-516b-aafa-70d2670c0337"

[compat]
CatViews = "1.0.0"
DataStructures = "0.17, 0.18"
Interpolations = "0.14.7"
JavaCall = "0.7.8"
julia = "1"